chore: update java SDK to OpenAPI Generator 6.0.1
ory/sdk pull request #210
Opened 2022-09-08 11:34 UTC by jonas-jonas

## Related Issue or Design Document

Related to #209 

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

## Further comments

2022-09-09 06:55 UTC, aeneasr requested changes
Nice! YOu still need to update the version for openapi for java in the scripts/generate file :)

2022-09-09 08:00 UTC, jonas-jonas commented
I was actually thinking about how we can make this process a bit easier for the future. Maven is quite limiting in what it allows to be shared across multiple `pom.xml`s and in general I'd prefer using Gradle instead. There are a few articles on releasing to maven central from Gradle here:

- https://www.jetbrains.com/help/space/publish-artifacts-from-a-gradle-project.html#publish-maven-artifacts-from-jetbrains-teamcity
- https://www.albertgao.xyz/2018/01/18/how-to-publish-artifact-to-maven-central-via-gradle/

This would have the benefit that we can manage external dependency versions & the publishing tasks in one central place and then just include/copy it in the generation process. I'd be happy to look into this, but I think there are other priorities for now ;)

As an aside: Open API already generates Gradle files, so it's just a matter of adjusting those. I'll open an issue here for it if that's fine with you and there was no specific reason for using maven here.

> Nice! YOu still need to update the version for openapi for java in the scripts/generate file :)

I think this is it, right?

https://github.com/ory/sdk/pull/210/files#diff-25806c0c4c68cee274f0c43c1b0ed2c9579bea4c3816903bfad038249cf7e934R70

2022-09-12 10:16 UTC, aeneasr commented
> As an aside: Open API already generates Gradle files, so it's just a matter of adjusting those. I'll open an issue here for it if that's fine with you and there was no specific reason for using maven here.

Perfect! Let's do that

2022-09-12 10:16 UTC, aeneasr approved these changes

2022-09-12 10:16 UTC, merged